src/tweetme/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

from tweets.views import TweetListView
from .views import home

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', TweetListView.as_view(), name='home'),
    url(r'^tweet/', include('tweets.urls', namespace='tweet')),
    url(r'^api/tweet/', include('tweets.api.urls', namespace='tweet-api')),
]

if settings.DEBUG:
	urlpatterns += (static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))

src/tweets/api/urls.py
from django.conf.urls import url
from django.views.generic.base import RedirectView

from .views import (
	TweetCreateAPIView,
    TweetListAPIView
    )

urlpatterns = [
    url(r'^$', TweetListAPIView.as_view(), name='list'), # /api/tweet/
    url(r'^create/$', TweetCreateAPIView.as_view(), name='create'), # /api/tweet/create/
    # url(r'^(?P<pk>\d+)/$', TweetDetailView.as_view(), name='detail'), # /tweet/1/
    # url(r'^(?P<pk>\d+)/edit$', TweetUpdateView.as_view(), name='edit'), # /tweet/1/
    # url(r'^(?P<pk>\d+)/delete$', TweeDeleteView.as_view(), name='delete'), # /tweet/1/
]

src/tweets/urls.py
from django.conf.urls import url
from django.views.generic.base import RedirectView

from .views import (
    TweetCreateView,
    TweetDetailView, 
    TweeDeleteView,
    TweetListView,
    TweetUpdateView
    )

urlpatterns = [
    #url(r'^admin/', admin.site.urls),
    url(r'^$', RedirectView.as_view(url='/')),#/tweet/
    url(r'^search/$', TweetListView.as_view(), name='list'), # /tweet/search
    url(r'^create/$', TweetCreateView.as_view(), name='create'), # /tweet/create/
    url(r'^(?P<pk>\d+)/$', TweetDetailView.as_view(), name='detail'), # /tweet/1/
    url(r'^(?P<pk>\d+)/edit$', TweetUpdateView.as_view(), name='edit'), # /tweet/1/
    url(r'^(?P<pk>\d+)/delete$', TweeDeleteView.as_view(), name='delete'), # /tweet/1/
]

src/accounts/models.py
from django.db import models

# Create your models here.

src/tweets/models.py
from django.conf import settings
from django.db import models

# Create your models here.

from .validators import validate_content

class Tweet(models.Model):
    user        = models.ForeignKey(settings.AUTH_USER_MODEL)
    content     = models.CharField(max_length=140, validators=[validate_content])
    updated     = models.DateTimeField(auto_now=True)
    timestamp   = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.content)

    def get_absolute_url(self):
        return "/tweet/%i/" % self.id

    # def clean(self, *args, **kwargs):
    #   content = self.content
    #   if content == "abc":
    #       raise ValidationError("Content Cannot be ABC")
    #   return super(Tweet, self).clean(*args, **kwargs)

src/tweets/forms.py
from django import forms


from .models import Tweet

class TweetModelForm(forms.ModelForm):
    content = forms.CharField(label='',
                              widget=forms.Textarea(
                                    attrs={'placeholder': 'Your message',
                                    'class': 'form-control'}
                                ))
    class Meta:
        model = Tweet
        fields = [
            "content"
        ]

    # def clean_content(self, *args, **kwargs):
    #   content = self.cleaned_data.get("content")
    #   if content == "abc":
    #       raise forms.ValidationError("Cannot be ABC")
    #   return content

src/accounts/views.py
from django.shortcuts import render

# Create your views here.

src/tweetme/views.py
from django.shortcuts import render


def home(request):
	return render(request, "home.html", {})

src/tweets/api/views.py
from django.db.models import Q
from rest_framework import generics
from rest_framework import permissions

from .serializers import TweetModelSerializer
from tweets.models import Tweet


class TweetCreateAPIView(generics.CreateAPIView):
    serializer_class = TweetModelSerializer
    permission_classes = [permissions.IsAuthenticated]

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)



class TweetListAPIView(generics.ListAPIView):
    serializer_class = TweetModelSerializer 

    def get_queryset(self, *args, **kwargs):
        qs = Tweet.objects.all().order_by("-timestamp")
        query = self.request.GET.get("q", None)
        if query is not None:
           qs = qs.filter(
                Q(content__icontains=query) |
                Q(user__username__icontains=query)
            ) 
        return qs

src/tweets/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (
    DetailView, 
    ListView, 
    CreateView, 
    UpdateView,
    DeleteView
)

from .forms import TweetModelForm
from .mixins import FormUserNeededMixin, UserOwnerMixin
from .models import Tweet

# Create your views here.

class TweetCreateView(LoginRequiredMixin, FormUserNeededMixin, CreateView):
    form_class = TweetModelForm
    template_name = "tweets/create_view.html"
    success_url = reverse_lazy("tweet:list")
    login_url = '/admin/'

class TweetUpdateView(LoginRequiredMixin, UserOwnerMixin, UpdateView):
    queryset = Tweet.objects.all()
    form_class = TweetModelForm
    template_name = "tweets/update_view.html"
    success_url = "/tweet/"

class TweeDeleteView(LoginRequiredMixin, UserOwnerMixin, DeleteView):
    queryset = Tweet.objects.all()
    model = Tweet
    success_url = reverse_lazy("tweet:list")
    template_name = "tweets/delete_confirm.html"

class TweetDetailView(DetailView):
    queryset = Tweet.objects.all()
    template_name = "tweets/detail_view.html"

    def get_object(self):
        pk = self.kwargs.get("pk")
        return Tweet.objects.get(id=pk)

class TweetListView(ListView):
    queryset = Tweet.objects.all()
    template_name = "tweets/list_view.html"

    def get_queryset(self, *args, **kwargs):
        qs = Tweet.objects.all()
        query = self.request.GET.get("q", None)
        if query is not None:
           qs = qs.filter(
                Q(content__icontains=query) |
                Q(user__username__icontains=query)
            ) 
        return qs

    def get_context_data(self, *args, **kwargs):
        context = super(TweetListView, self).get_context_data(*args, **kwargs)
        context['create_form'] = TweetModelForm()
        context['create_url'] = reverse_lazy("tweet:create")
        return context

src/templates/base.html
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>{% block title %}Tweetme.co{% endblock title %}</title>

    <!-- Bootstrap -->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">


    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <style>
      .red-color {
        color: red;
      } 

      .grey-color {
        color: #ccc;
      }
    </style>
  </head>
  <body>
    {% include "navbar.html" %}
    <div class="container">
      {% block content %}{% endblock content %}
    </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    {% block script %}{% endblock script %}

    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <!-- Latest compiled and minified JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>
</html>

src/templates/home.html
{% extends "base.html" %}

{% block title %}{{ block.super }} | Welcome{% endblock title %}

{% block content %}
<h1>Puppies!</h1>
{% endblock content %}

src/templates/navbar.html
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'home' %}">Tweetme</a>
    </div>
    {% include 'tweets/tweet_search_form.html' %}

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

src/tweets/templates/tweets/create_view.html
{% extends "base.html" %}

{% block content %}
	<div class="row">
		<div class="col-sm-8 col-sm-offset-2">
			<h1>Create Tweet</h1>
			{% include "tweets/form.html" with form=form btn_title='Tweet' %}
		</div>
	</div>

{% endblock content %}

src/tweets/templates/tweets/delete_confirm.html
{% extends "base.html" %}

{% block content %}
	<form action="" method="post">
		{% csrf_token %}
	    <p>Are you sure you want to delete "{{ object }}"?</p>
	    <input type="submit" value="Confirm" />
	</form>
{% endblock content %}

src/tweets/templates/tweets/detail_view.html
{% extends "base.html" %}

{% block content %}
    <div class="col-sm-3 col-xs-12" style="background-color: yellow;">
        <h1>{{ object.user }}</h1>
    </div>
    <div class="col-sm-9 col-xs-12">
            
        <div class="media">
          {% if tweet.image %}
            <img class="d-flex mr-3" src="..." alt="Generic placeholder image">
          {% endif %}
          <div class="media-body">
            {{ object.content }}<br>
            Published: {{ object.updated|date }}
          </div>
        </div>
    </div>
{% endblock content %}

src/tweets/templates/tweets/form.html
<form method="POST" {% if form_id %}id="{{ form_id }}"{% endif %}  action="{% if action_url %}{{ action_url }}{% endif %}" accept-charset="utf-8">
	{% csrf_token %}
	{{ form.as_p }}
	<input class="btn btn-primary" type="submit" value="{{ btn_title }}">
</form>

src/tweets/templates/tweets/list_view.html
{% extends "base.html" %}

{% block script %}
	<script>
		function getURLParameter(name) {
		  return decodeURIComponent((new RegExp('[?|&]' + name + '=' + '([^&;]+?)(&|#|;|$)').exec(location.search) || [null, ''])[1].replace(/\+/g, '%20')) || null;
		}

		$(document).ready(function(){
			var query = getURLParameter("q");
			var tweetList = [];
			function parseTweets(){
				//parse and display tweets or message if no tweets exist yet.
				if( tweetList.length > 0 ){
						
					$.each(tweetList, function(key, value){
						attachTweet(value);
					});
				} else {
					var msg = "<p>No tweets have been added yet.</p>";
					if( query ){
						msg = "<p>No search results found.</p>";
					}
					$("#tweet-list").append(msg);		
				}
			}

			function attachTweet(tweetValue, prepend = false){
				var content = tweetValue.content;
				var user = tweetValue.user;
				var tweetDate = tweetValue.date_display;
				var tweetHtml = "<div class='media'>"+
						  "<div class='media-body'>"+ content +
						    "<br><span class='mt-0'>via " + user.username + "</span>" +
						    " | "+ tweetDate + " | <a href='#'>View</a><br>"+
						  "</div></div><hr>";
				if( prepend===true ){
					$("#tweet-list").prepend(tweetHtml);
				} else {
					$("#tweet-list").append(tweetHtml);
				}
			}

			function fetchTweets(){
				$.ajax({
					url: "{% url 'tweet-api:list' %}",
					data: {
						"q": query
					},
					method: "GET",
					success: function(data){
						tweetList = data;
						parseTweets();

					},
					error: function(data){
						console.log(data);
						alert("error");
					}
				});
			}

			fetchTweets();

			var charsStart = 140;
			var charsCurrent = 0;

			$("#tweet-form").append("<span id='tweetCharsLeft'>" + charsStart + "</span>");

			$("#tweet-form textarea").keyup(function(e){
				var tweetValue = $(this).val();
				charsCurrent = charsStart - tweetValue.length;
				$("#tweetCharsLeft").text(charsCurrent);
				var spanChars = $("#tweetCharsLeft");
				spanChars.text(charsCurrent);

				if( charsCurrent > 0 ) {
					spanChars.removeClass("grey-color");
					spanChars.removeClass("red-color");
				} else if ( charsCurrent == 0 ){
					spanChars.addClass("grey-color");
					spanChars.removeClass("red-color");
				} else if ( charsCurrent < 0 ) {
					spanChars.addClass("red-color");
					spanChars.removeClass("grey-color");
				}
			});

			$("#tweet-form").submit(function(e){
				e.preventDefault();
				var this_ = $(this);
				var formData = this_.serialize();
				if (charsCurrent >= 0){
					$.ajax({
						url: "/api/tweet/create/",
						data: formData,
						method: "POST",
						success: function(data){
							$("#id_content").val("");
							attachTweet(data, true);
						},
						error: function(data){
							console.log(data);
							alert(data.status + ": " + data.statusText);
						}
					});
				} else {
					alert("Your tweet is too long!");
				}
			});
		});
	</script>
{% endblock script %}

{% block content %}


	<div class="row">
		<div class="col-sm-3 col-xs-12" style="background-color: red;">
			<h1>{{ request.user }}</h1>
		</div>
		<div class="col-sm-9 col-xs-12">
			{% if not request.GET.q %}
				{% include "tweets/form.html" with form=create_form action_url=create_url form_id="tweet-form" btn_title='Tweet' %}
			{% endif %}
			<hr>

			<div id="tweet-list">
				
			</div>
		</div>
	</div>
	
{% endblock content %}

src/tweets/templates/tweets/tweet_search_form.html
<form class="navbar-form navbar-left" action='{% url "tweet:list" %}' method="get" accept-charset="utf-8">
	<div class="form-group">
		<input class="form-control" type="text" name="q" placeholder="Your Search" value="{{ request.GET.q }}">
	</div>
	<input class="btn btn-default" type="submit" value="Search">
</form>

src/tweets/templates/tweets/update_view.html
{% extends "base.html" %}

{% block content %}

	{% include "tweets/form.html" with form=form btn_title='Edit' %}

{% endblock content %}